name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Compile shampoo.cpp
      run: g++ -o Shampoo Shampoo.cpp

    - name: Run Shampoo.cpp
      run: ./Shampoo