name: Generate Documentation

on:
  push:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

   - name: Check Documentation Directory
     run: dir docs\html

    - name: Install Doxygen
      run: |
        choco install doxygen.install --version=1.9.1

    - name: Generate Doxygen Documentation
      run: doxygen Doxyfile

    - name: Upload Documentation
     uses: actions/upload-artifact@v3
     with:
       name: docs
       path: docs/html

